# Generated by Django 5.2.3 on 2025-12-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
