# Generated by Django 5.2.3 on 2025-12-17 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_sms_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
